Add JDL Parser and Queries
2023-2024-PROJET-S10-G10/app pull request #18
Opened 2024-03-06 13:57 UTC by STACKL0RD

* JDL Parser code + tests
* Configuation DB
* Queries + tests

2024-03-06 14:26 UTC, KillianGricourt requested changes

2024-03-06 14:26 UTC, KillianGricourt commented on Parser/jdl_parser.py
> +#from utils.jdl import jdlKeys
Commented code shouldn't stay here

2024-03-06 14:26 UTC, KillianGricourt commented on SQL/Config_BDD.py
> +        #conn.execute(insert(cluster_table).values(name="Luke", api_url="/prout", api_username="dova", api_password="zer", batch=api(1), api_auth_type="pouet"))
???

2024-03-06 14:26 UTC, KillianGricourt commented on SQL/queries.py
> +"""
idem

2024-03-06 14:26 UTC, KillianGricourt commented on Test/TestJdlParser.py
> +#class OneParameterJdlUT(TestManager):
?

2024-03-06 14:26 UTC, KillianGricourt commented on Test/TestJdlParser.py
> +#class SeveralParameterJdlUT(TestManager):
?

2024-03-08 09:18 UTC, KillianGricourt submitted a review, later dismissed
Ok

2024-03-08 09:30 UTC, DiegoCDO approved these changes

2024-03-08 09:30 UTC, merged